### ISSUE TITLE
Toggles for speed-up and encounters seem stuck in "on"

### ISSUE THREAD

**Issue by GuyInDogSuit** [Albeoris/Memoria.FFPR#10]
I don't know how else to replicate this, it could just be my keyboard/Windows setup, but I'm playing with gamepad and I can't seem to disable these now. The only thing that seems to end it is closing the game entirely. Are there logs I can upload?

**Comment by Albeoris** [comment]
> but I'm playing with gamepad and I can't seem to disable these now. The only thing that seems to end it is closing the game entirely. Are there logs I can upload?

Explain how you turn on the speed and how you turn it off? 
If you have configure it to a game action (ToggleAction, HoldAction), show your config file.
Is the problem being reproduced now? If so, I will build a special release for you with improved logging.

**Comment by GuyInDogSuit** [comment]
Nope, I haven't changed any options in the config files.
So F1 is still speed-up, F2 is still encounters on/off, etc.

**Comment by Albeoris** [comment]
Need more information to reproduce.
How do you enable this option on the gamepad? How do you try to turn it off?

**Comment by DCSpecial** [comment]
Game only Monitors Keyboard while focused, Gamepad interaction still works unfocused. Maybe OP Alt+Tabs?

**Comment by Albeoris** [comment]
Sounds like a reason. 
I will close the issue until the author returns. (@GuyInDogSuit)

**Comment by GuyInDogSuit** [comment]
> Game only Monitors Keyboard while focused, Gamepad interaction still works unfocused. Maybe OP Alt+Tabs?

I had realized that, as well, and remedied _that_ particular issue by forcing gamepad focus to it using a hotkey from DisplayFusion.

But whether naturally focused or not, the issue with gamepad toggles still persists.

**Comment by Albeoris** [comment]
> remedied _that_ particular issue
> the issue with gamepad toggles still persists.

Please explain what problem remains if you write that you solved it by switching the focus to the game?
