### ISSUE TITLE
Extracting/streaming "scripts"

### ISSUE THREAD

**Issue by nic0lette** [Albeoris/Memoria.FFPR#13]
Just wondering if it would be possible to extract the "scripts" that are referenced in some of the extracted csv files. For example, "map_script.csv" references scripts named "sc_map_<val>", but those assets aren't (yet) present in the export.

Thank you for your work on the project =D

**Comment by nnguyen259** [comment]
The latest version should already had it. They are in `Serial/Res/Map`

**Comment by nic0lette** [comment]
Oh! I just completely missed that. Thank you =D
