### ISSUE TITLE
Issues with Exporting Enabled

### ISSUE THREAD

**Issue by Orionx365** [Albeoris/Memoria.FFPR#14]
Hi, I've been having issues getting FF1 to export its files. After putting the loader and the FF1 specific Memoria files in their correct locations (for me, F:\SteamLibrary\steamapps\common\FINAL FANTASY PR), I launch FF1 and close the game.  The config file, "Memoria.ffpr.cfg" is generated. I open the file and set ExportEnabled = true.  The export directory is %StreamingAssets% as it is by default.

I launch FF1, and the miniature window which would show the export progress (which iicr, is out of 800 files or so) only displays for half a second before vanishing. Nothing shows up in the StreamingAssets folder. This is very strange to me, as this all worked properly on a friend's computer.

edit: 
I've attached my LogOutput. Additionally, I noticed that the F1 and F2commands aren't working either.

[LogOutput.log](https://github.com/Albeoris/Memoria.FFPR/files/6958011/LogOutput.log)

**Comment by Orionx365** [comment]
Resolved - I just needed to restart my computer.

**Comment by devonfae** [comment]
This happened to me when attempting to run the game without an internet connection. Turning on internet and logging into Steam made Memoria function properly. My guess is that Steam's DRM interferes with the operation, so Memoria will not function in Steam's offline mode.
