### ISSUE TITLE
100% collision with Warmech (100% столкновение с Warmech)

### ISSUE THREAD

**Issue by LoveIsDarkness** [Albeoris/Memoria.FFPR#18]
Located in the Flying Fortress on the bridge leading to Tiamat, it has a 3 in 64 chance of appearing each time the Warriors of Light enter a battle there

**Comment by Albeoris** [comment]
### Investigation:

1. Export game resources:
```
1. Edit \FINAL FANTASY PR\BepInEx\config\Memoria.ffpr.cfg
2. ExportEnabled = true
3. Run the game and wait for the export to complete.
```

2. Use Notpad++, Far Manager, Total Commander, etc. to find substring `Warmech` in all of exported assets:
```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Message\system_en.txt

MSG_MON_NAME_119	Warmech
```

3. Looking for `MSG_MON_NAME_119`:
```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Master\monster.csv

ID: 119
mes_id_name: MSG_MON_NAME_119
```

4. There is another monster*.csv files `monster_set.csv` looks like what we want.
```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Master\monster_set.csv

BUT there is no number 119 here. :(
And instead of monster_id, there is a monster_set in the header. O.o

ID:50	
monster_set1: 780
```

5. OK, looking for 780 leads us to `monster_party.csv`:
```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Master\monster_party.csv

And there is 119 in the "monster8" header.
ID: 261
monster8: 119
```

### Success:
6. Go back to `monster_set.csv` and searching for 261 (party id from `monster_party.csv`):

```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Master\monster_set.csv

Yahooo! We found it!
ID: 33
monster_set14: 261
monster_set14_rate: 10
```

### Validation:

7. Ok, now we can set monster_set14_rate to 100 or/and change all of monster_set1...13 to 261
But let's make sure we find the encounter we really need.
Looking for ,33, (ID from `monster_set.csv`):
```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Master\map.csv

id	map_name	asset_name	map_title	script_id	bgm_id	reverb_flag	environmental_se_id	required_steps_min	required_steps_max	subtract_steps	monster_set_id

ID: 112
map_title: MSGARA_NAME_10
monster_set_id: 33
```

8. Looking for MSGARA_NAME_10
```
\FINAL FANTASY PR\FINAL FANTASY_Data\StreamingAssets\Assets\GameAssets\Serial\Data\Message\system_en.txt

MSG_MAP_NAME_28	Flying Fortress
MSGARA_NAME_10	5F
```

That's right, we're great! :)

**Comment by Albeoris** [comment]
Unpack one of the archives into the game folder. 

[Flying Fortress 5F - All Warmechs.zip](https://github.com/Albeoris/Memoria.FFPR/files/7828509/Flying.Fortress.5F.-.All.Warmechs.zip)
[Flying Fortress 5F - Warmech 100.zip](https://github.com/Albeoris/Memoria.FFPR/files/7828510/Flying.Fortress.5F.-.Warmech.100.zip)

**Comment by Albeoris** [comment]
Partial CSV:

[Flying Fortress 5F - All Warmechs.zip](https://github.com/Albeoris/Memoria.FFPR/files/7866825/Flying.Fortress.5F.-.All.Warmechs.zip)
[Flying Fortress 5F - Warmech 100.zip](https://github.com/Albeoris/Memoria.FFPR/files/7866826/Flying.Fortress.5F.-.Warmech.100.zip)
