### ISSUE TITLE
No Random Encounters after installing FF6 version

### ISSUE THREAD

**Issue by TehLostOne** [Albeoris/Memoria.FFPR#24]
Title, turning on speed with F1 works fine. F2 will trigger 'e' to appear on screen, and remove it, but always has no encounters

**Comment by Kyunghoonie** [comment]
Having the same issue. Installed Memoria after starting the game and then "random encounters" were gone. Toggling with F2  makes no difference. Deleting the FF6 mod turns "random encounters" back on.

**Comment by chappellkm** [comment]
Happening here as well. If it is at all helpful, I've attached my log.

[LogOutput.log](https://github.com/Albeoris/Memoria.FFPR/files/8127930/LogOutput.log)

**Comment by fallacies-GitHub** [comment]
Having the same issue. Log attached.
[LogOutput.log](https://github.com/Albeoris/Memoria.FFPR/files/8131626/LogOutput.log)

**Comment by Albeoris** [comment]
```C#
[Error  :    Detour] System.BadImageFormatException: Method with open type while not compiling gshared
File name: 'Assembly-CSharp'
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) CheckEncount(intptr,intptr,intptr*,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
```

**Comment by johnathandrozdowski** [comment]
Same issue. 
[LogOutput.log](https://github.com/Albeoris/Memoria.FFPR/files/8135412/LogOutput.log)

**Comment by Albeoris** [comment]
https://github.com/BepInEx/BepInEx/issues/366
