### ISSUE TITLE
Improve Instructions in the Main mod page 

### ISSUE THREAD

**Issue by faospark** [Albeoris/Memoria.FFPR#26]
change 
4.Navigate to InstallDir\BepInEx\config and open Memoria.ffpr.cfg

to
4.Navigate to InstallDir\BepInEx\config\Memoria.FFPR\ and open Assets.cfg

**Comment by Albeoris** [comment]
Done!
https://github.com/Albeoris/Memoria.FFPR/commit/986b1284003fc05b53ebde363564af55a275cef1
