### ISSUE TITLE
Where are Magicite Level-Up Bonuses stored?

### ISSUE THREAD

**Issue by fallacies-GitHub** [Albeoris/Memoria.FFPR#27]
Not sure if this is the right place to ask, but I haven't been able to find the location of the Magicite Level-Up Bonuses.
The names of the Level-Up Bonuses are stored in Message/system_en.txt, but that isn't terribly helpful in determining how to edit them.

For reference, the relevant section in system_en.txt

> MSG_MAG_INF_138	+10% bonus to HP increase at next level-up
> MSG_MAG_INF_139	+30% bonus to HP increase at next level-up
> MSG_MAG_INF_140	+50% bonus to HP increase at next level-up
> MSG_MAG_INF_141	+10% bonus to MP increase at next level-up
> MSG_MAG_INF_142	+30% bonus to MP increase at next level-up
> MSG_MAG_INF_143	+50% bonus to MP increase at next level-up
> MSG_MAG_INF_144	Strength +1 at next level-up
> MSG_MAG_INF_145	Strength +2 at next level-up
> MSG_MAG_INF_146	Speed +1 at next level-up
> MSG_MAG_INF_147	Stamina +1 at next level-up
> MSG_MAG_INF_148	Stamina +2 at next level-up
> MSG_MAG_INF_149	Magic +1 at next level-up
> MSG_MAG_INF_150	Magic +2 at next level-up
> MSG_MAG_INF_151	HP +10%
> MSG_MAG_INF_152	HP +30%
> MSG_MAG_INF_153	HP +50%
> MSG_MAG_INF_154	MP +10%
> MSG_MAG_INF_155	MP +30%
> MSG_MAG_INF_156	MP +50%
> MSG_MAG_INF_157	Level +30%
> MSG_MAG_INF_158	Level +50%
> MSG_MAG_INF_159	Strength +1
> MSG_MAG_INF_160	Strength +2
> MSG_MAG_INF_161	Speed +1
> MSG_MAG_INF_162	Stamina +1
> MSG_MAG_INF_163	Stamina +2
> MSG_MAG_INF_164	Magic +1
> MSG_MAG_INF_165	Magic +2

Maybe I'm failing to see something, but a search of the directory for the text string ",50," (without quotation marks) for HP +50% turns up 4393 results in 577 files. I haven't looked through them exhaustively, but a cursory inspection turns up nothing of use.
"strength" turns up 45 results in 12 files, but none of them are very useful.
message_conclusion.csv gives 4 results for "LEVEL" but all of these are just system message displays.
"素早さ" (Speed) produces results only in Message/story_mes_ja.txt and Message/system_ja.txt, which isn't helpful.
"ＨＰ" (in full-width Japanese alphanumeric) turns up results in common_master.json and the enemy AI for the Ultima Weapon. The former looks to be the text caption of some code that assesses whether the party is alive. 

Not really sure where I should be looking. Any pointers?

**Comment by Albeoris** [comment]
```c#
	public enum ParameterType
	{
		Non, // 0
		Level, // 1
		HP,  // 2
		MP, // ....
		Power,
		Vitality,
		Agility,
		Weight,
		Intelligence,
		Spirit,
		Attack,
		Defense,
		AbilityDefense,
		AbilityEvasionRate,
		Magic,
		Luck,
		AccuracyRate,
		EvasionRate,
		AbilityDisturbedRate,
		CriticalRate,
		MagicCount,
		DamageDiemeter,
		AttackSpeed,
		DefenseCount,
		MagicDefenseCount,
		AccuracyCount = 202,
		AbilityDefenseRate,
		EvasionCount,
		JobLevel = -1
	}
```

**Comment by Silvris** [comment]
Just confirmed it myself; Magicite level up bonuses and summon ability index (the ability in ability.csv that corresponds to the summon) are hardcoded within the constructor of Serial.FF6.Management.MagicStoneData.

**Comment by Albeoris** [comment]
[Now](https://github.com/Albeoris/Memoria.FFPR/commit/f7f664cb13c98f8f5252ecb6aee352198ab44ff9) you can change it.

**Assets.cfg**
```ini
[Assets]
ExportDirectory = %StreamingAssets%
ImportDirectory = %StreamingAssets%
ModsEnabled = true
ModsDirectory = %StreamingAssets%/Mods
ExportMagicite = true
ImportMagicite = true
```

**\StreamingAssets\Mods\MyMagiciteTest\Memoria\Magicite.json**
```json
[
  /*Ramuh*/
  /*Vitality +1*/
  {
    "Id": 62,
    "AbilityId": 1504, /* Fireball */
    "ParameterType": "Vitality",
    "ParameterValue": 2000, /* +1 -> +2000 */
    "DescriptionKey": "MSG_MAG_INF_162 -> 2000" /* change value in magicite bonus text to 2000 */
  }
]
```

**Comment by aruteoso** [comment]
Magicite.json is not output to the Memoria folder after setting Assets.cfg.
[Assets]
ExportEnabled = true
ExportText = true
ModsEnabled = true
ModsDirectory = %StreamingAssets%/Mods
ExportMagicite = true
ImportMagicite = true
