### ISSUE TITLE
FF5 New Game Stuck

### ISSUE THREAD

**Issue by princedarkly** [Albeoris/Memoria.FFPR#29]
Can't start a new game or load a saved game on FF5 when Memoria is installed. Stuck at black screen.

**Comment by Albeoris** [comment]
Share the logs please.

**Comment by Albeoris** [comment]
![image](https://user-images.githubusercontent.com/4787832/155854201-a1dfc462-9b97-4197-ac37-06e654fb36b9.png)

Just checked it.
Everything works fine.
