### ISSUE TITLE
ff6pr hotkeys problem

### ISSUE THREAD

**Issue by NeonLightning** [Albeoris/Memoria.FFPR#31]
when i have forced combat L+R doesn't do anything,
and no hotkeys seem to be working. i can't frameskip or enable highlighting

**Comment by NeonLightning** [comment]
also if i have the config files open in notepad++ when i close the game and look at them again it says something changed but nothing has changed

**Comment by Albeoris** [comment]
> also if i have the config files open in notepad++ when i close the game and look at them again it says something changed but nothing has changed

It's normal. Every time when you launch the game, config files are overwritten.

**Comment by Albeoris** [comment]
> when i have forced combat L+R doesn't do anything, and no hotkeys seem to be working. i can't frameskip or enable highlighting

To escape, use the character switch buttons. 

What is L+R? What keys are you pressing?
And for framespeed and highlighting?

Please show your file with hot keys settings.

**Comment by Albeoris** [comment]
@NeonLightning , do you use a laptop? Maybe functional (Fn) keys is the reason? 
Feel free to open the issue again if you have new information.

**Comment by NeonLightning** [comment]
idk how to fix it though.
`[Highlighting]

## Enables or disables highlighting of interactive objects.
# Setting type: HotkeyGroup
# Default value: CapsLock; CapsLock(Hold)
# Acceptable keys: Ctrl+Alt+Shift+Key(Hold): https://docs.unity3d.com/ScriptReference/KeyCode.html
# Acceptable actions: Ctrl+Alt+[Action]+[Action]: [None], [Enter], [Cancel], [Shortcut], [Menu], [Up], [Down], [Left], [Right], [SwitchLeft], [SwitchRight], [PageUp], [PageDown], [Start]
HighlightingKey = JoystickButton8; CapsLock(Hold)

## Allowed types of highlighted icons.
# Setting type: IReadOnlyList`1
# Default value: GetOn, TreasureBox
# Acceptable values: None, Talk, GetOn, GetOff, TreasureBox, GetOnShip, TreasureBoxOff
HighlightingIcons = GetOn, TreasureBox

## Pressing the key highlights hidden passages.
# Setting type: Boolean
# Default value: false
HighlightHiddenPassages = true

`

`[Speed]

## Speed up key.
# Setting type: HotkeyGroup
# Default value: F1; F1(Hold)
# Acceptable keys: Ctrl+Alt+Shift+Key(Hold): https://docs.unity3d.com/ScriptReference/KeyCode.html
# Acceptable actions: Ctrl+Alt+[Action]+[Action]: [None], [Enter], [Cancel], [Shortcut], [Menu], [Up], [Down], [Left], [Right], [SwitchLeft], [SwitchRight], [PageUp], [PageDown], [Start]
Key = JoystickButton9+JoystickButton4; JoystickButton9(Hold)

## Speed up toggle factor.
# Setting type: Single
# Default value: 3
# Acceptable value range: From 0.01 to 10
ToggleFactor = 2

## Speed up hold factor.
# Setting type: Single
# Default value: 5
# Acceptable value range: From 0.01 to 10
HoldFactor = 4

`
`[Battle.System]

## Allows to override the combat system using the settings below. Some combat mechanics may have changed.
# Setting type: Boolean
# Default value: false
ChangeBattleType = false

## Overrides the combat system if ChangeBattleType is true.
# Setting type: BattleType
# Default value: Command
# Acceptable values: ATB, Command
BattleType = Command

`
and now it seems like memoria just isn't working period. none of my hotkeys are working again for it. but my one for bepinex config manager pops up.
