### ISSUE TITLE
Partial TXT import possible?

### ISSUE THREAD

**Issue by saftle** [Albeoris/Memoria.FFPR#33]
I'm personally working on a 2nd mod now that makes changes to the system_en.txt, however on different lines. I'm also appending new lines in one of the mods.

Would it be possible in the future to have partial txt imports? Thank you!

**Comment by Albeoris** [comment]
Sure, it's possible.

**Comment by Albeoris** [comment]
Done: https://github.com/Albeoris/Memoria.FFPR/commit/55620508ad337f92d2b381236260ada0df7781cf

```
[Info   :Memoria IL2CPP] [Mod] Merging data from %StreamingAssets%\Mods\0001_MyTextMod\Assets/GameAssets/Serial/Data/Message/system_us.txt
[Info   :Memoria IL2CPP] [Mod] Changed message [MSG_SYSTEM_276]: [New Game] -> [Hello World!]
```

You can build the latest or wait for the next release.

**Comment by saftle** [comment]
Awesome. Thank you very much!
