### ISSUE TITLE
Hexadecimal color from config being replaced on input

### ISSUE THREAD

**Issue by Silvris** [Albeoris/Memoria.FFPR#35]
When reading color from config, it will reset to "white" when reading any hexadecimal color string. Colors with defined names such as "cyan" are not effected. I believe the cause of this is line 123 of ColorTypeConverter, where it should be if(!ColorUtility.TryParseHtmlString) instead of if(ColorUtility.TryParseHtmlString).

**Comment by Albeoris** [comment]
You are absolutly right! Thank you!
