### ISSUE TITLE
Export Fails, Memoria Doesn't Load

### ISSUE THREAD

**Issue by Temperhoof** [Albeoris/Memoria.FFPR#38]
Unable to successfully export Assets or utilize Function Keys in-game (Final Fantasy 4 Pixel Remaster), Export appears momentarily upon load, but never gets past 0.00% -- then promptly vanishes.

Literally tried everything:

> Did latest version of BeInEX Bleeding Edge
> Tried FF4 and FF6 Memoria Loaders
> Disabled DEP (Data Execution Prevention}
> Disabled Firewalls
> Disabled Anti-malware
> Whitelisted Folder and all assets
> Turned off all background processes on system
> Booted System into SAFE MODE to ensure all processes were disabled
> Uninstalled Game and did a Fresh Install
> Tried with edited mod UnityPlayer.dll and vanilla UnityPlayer.dll
> Deleted all assets and tried again 10+ different times, no success.
> Others on the FF Mod Discord are now reporting similar problems.

=====

Each time I get the same error message on the Log:

[Message:Memoria FF PR] The mod has been successfully initialized.
[Message:   BepInEx] Chainloader startup complete
[Error  :Unhollower] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: void Last.Management.ResourceManager.DestroyGroupAsset(string,Il2CppSystem.Collections.Generic.List`1<string>)
  at (wrapper dynamic-method) Memoria.FFPR.IL2CPP.ResourceExporter.Trampoline_VoidThisMemoria.FFPR.IL2CPP.ResourceExporterUpdate(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
[Info   :Memoria IL2CPP] [ContentCatalogData_CreateLocator] Resource file extensions have been successfully parsed.
[Info   :Memoria IL2CPP] [Export] Export stopped.
[Info   :Memoria IL2CPP] [ModComponent].OnDestroy(
[LogOutput.log](https://github.com/Albeoris/Memoria.FFPR/files/8358420/LogOutput.log)

**Comment by Albeoris** [comment]
Fixed in the latest version.
