### ISSUE TITLE
Steam Deck: FF6 will crash if using the Quick Save kb shortcut after waking up from sleep.

### ISSUE THREAD

**Issue by outphase** [Albeoris/Memoria.FFPR#39]
I'm guessing the Steam Deck isn't loading memoria properly after waking up from sleep. The game will crash back to the Steam UI if I attempt to Quick Save with the keyboard shortcut after I have woken up from sleep. I finished a battle then attempted to Quick Save only to get kicked out back to the main menu.

Steps to reproduce:

0. Test out Quick Save. I have the F5 key bound to the rear L5 button. I get the Quick Save Complete text on screen.
1. Put the Deck to sleep with the power button.
2. Wake up the Deck
3. Press L5 again to try to Quick Save.
4. Crash to Steam UI

Note: not all keyboard shortcuts cause the crash. F1 to speed up seems to still work after waking up. I had 1 attempt of Quick Save actually not crash, but I had about 4+ crashes while testing it out.

**Comment by Albeoris** [comment]
@outphase , check the linked issue. Thank you, @Ryunam.
