### ISSUE TITLE
New Version is still creating FF1 Config File

### ISSUE THREAD

**Issue by Eatitup86** [Albeoris/Memoria.FFPR#4]
It looks like the new version creates both the Memoria.ff1.cfg and the Memoria.ffpr.cfg files when used on any version.

I am guessing it is only supposed to make the FFPR version.

**Comment by Albeoris** [comment]
Nope, you still have an old file. Delete it. :) 

![image](https://user-images.githubusercontent.com/4787832/127936040-3932498e-b62d-42c8-8da2-d410c590dd29.png)
