### ISSUE TITLE
Steam Deck: Memoria does not seem to work (tested on FF2)

### ISSUE THREAD

**Issue by Ryunam** [Albeoris/Memoria.FFPR#41]
Hi! When using the latest version of Memoria.FFPR on a Steam Deck device, I have noticed that the hotkeys defined in the BepInEx\config\Memoria.ffpr\$Section.cfg files are not working reliably. They do not seem to be detected at all in-game.

This is the same cfg file that I use on my Windows installation. On my Windows system all the hotkeys seem to work properly, but on a Steam Deck with the same configuration files there is no response at all when pressing any hotkey (for example, speedup doesn't work at all and encounters continue to happen). I have tried changing the hotkeys and remapping them to any of the physical buttons on the device, but there's no effect.

This problem was observed on FF2, but I'm not sure if it's also happening with the other titles. Might be partially related to this: https://github.com/Albeoris/Memoria.FFPR/issues/39

EDIT: Upon further testing, it seems the latest version of Memoria isn't loading at all when launched on a Steam Deck. I tried to perform a new install from scratch, but it seems Memoria isn't being loaded and is not generating the .cfg files.

**Comment by Ryunam** [comment]
Disregard this issue, I got it working. I was unaware of the fact that, in order to make Memoria FFPR work on Steam Deck or any Proton-based installation, there's an additional set of instructions that needs to be applied beforehand. See here for reference: https://docs.bepinex.dev/articles/advanced/steam_interop.html#open-winecfg-for-the-target-game

**Comment by arcath-** [comment]
For some reason, in addition to, I also needed to add `export WINEDLLOVERRIDES="winhttp=n,b"; %command%` to the launch option in steam for mapping F1 to actually work for speed up.
