### ISSUE TITLE
Memoria is broken for FF5 (in a different way than for FF4) as of 2024/01/30

### ISSUE THREAD

**Issue by sorlok** [Albeoris/Memoria.FFPR#49]
As of the latest Steam release, Memoria for FF5 is broken. Here's what I did to test this:
  * Completely uninstall FF5 and remove all files from the Steam FF5 directory.
  * Install FF5, then install Memoria (following the instructions on the Memoria page). This includes BepIn and the FF5 zip.
  * Start FF5 -- I did *not* extract resources, although this is possible.
  * Now, either load a save file or start a new game --the game will NOT allow you to walk around or open the menu. (If you start a new game, the game will respond to the first button press to close the Tutorial window, but that's it).
  * Memoria's key shortcuts (i.e., "no encounters") will still cause the notification ("e") to appear. And water animations on the world map still work. So the game's not frozen per se.

This is a different failure mode than was reported for FF4, FYI.

**Comment by Albeoris** [comment]
Fixed:
https://github.com/Albeoris/Memoria.FFPR/releases
