### ISSUE TITLE
Still getting Memoria.ff1.cfg when installing from scratch

### ISSUE THREAD

**Issue by Eatitup86** [Albeoris/Memoria.FFPR#9]
Hi there. Great work on this so far!

Every time I reinstall the next version it is still creating that Memoria.ff1.cfg file.

- This is the process I have been using for version updates:
- Delete BepInEx, mono, changelog.txt, doorstep_config.ini, and winhttp.dll
- Extract Loader_v2021.08.01 then FF#_v####.##.##
- Launch the game.

When I then navigate to BepInEx\Config both Memoria.ff1 & Memoria.ffpr config files are there.

**Comment by Eatitup86** [comment]
I think I see why that is happening. The Memoria.ff1 file is within the Loader_v2021.08.01 archive.

**Comment by Albeoris** [comment]
Fixed. Thank you!
